### PR TITLE
Fix ShellCheck CI

### PR DESCRIPTION
**Pull request by dakanji**

### CODE REVIEW

**Comment by dakanji** [comment]
@vit9696

Tested and Ready. Exit code from ShellCheck is returned so that the test fails when it should.

BTW, think your first instinct to stick with "which" is probably the correct one as there is a good reason why it is no longer flagged except specifically requested to.  So did the osx image to Catalina so as to load 0.7.1. If you agree, will implement in the other repos.

**Comment by vit9696** [comment]
To be honest, I am not too happy about xcode11 with one reason. When it ages and Travis CI stops supporting it we will need to update many repositories. On the other side using the default VM let's Travis themselves upgrade it. Perhaps it is better to let homebrew update and download 0.7.1 on 10.13?

As for `which` vs `command -v` I can live with whatever as long as it is consistent across the code.

**Comment by dakanji** [comment]
OK. Went for the Xcode as found examples using similar for images in other yml files.
Can let homebrew update albeit at a slight time cost.

**Comment by dakanji** [comment]
Done as per indicated preference but actually think using the Xcode Image is faster and cleaner in terms of output (easy to review and see what the issue is, if it fails, without a lot of "noise" as is currently the case)

Also not so sure about how critical the issue is given that updates will be needed on existing files at some point (Not really introducing a new item to consider) and such updates can be done together when that happens. Hopefully by then, the default is already an image with v0.7.1+ and update would just be a matter of deleting that line.

Just food for thought

**Pull request merged**
